### PR TITLE
Add :silent-failure? option

### PR DESCRIPTION
**Pull request by madvas**

### CODE REVIEW

**Comment by madvas** [comment]
Any problem with this?

**Comment by madvas** [comment]
ping

**Comment by danielcompton** [comment]
Can you give some more context on what situations would need this?

**Comment by superstructor** [comment]
Prior discussion was on issue #5 

Sorry for the delay in getting to this @madvas I'll resolve the conflicts and merge soon.

**Comment by superstructor** [comment]
After looking at the current code I see this is no longer relevant as of [cee15ec](https://github.com/day8/re-frame-forward-events-fx/commit/cee15ec7401440dce68d8349a35c9b1e2ee6019f) since [`re-frame/remove-post-event-callback`](https://github.com/day8/re-frame/blob/master/src/re_frame/router.cljc#L111) only warns in the equivalent situation. 

Therefore closing without merging. Thanks anyway for making the effort and apologies this took so long to close @madvas

**Pull request closed without merging**
